nyc_parking_violations_ntenorio:
  outputs:
    dev:
      type: duckdb
      path: '../data/nyc_parking_violations_ntenorio.db'
    prod:
      type: duckdb
      path: '../data/prod_nyc_parking_violations_ntenorio.db'
  target: dev